format = """
$username\
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

right_format = """$cmd_duration"""

add_newline = false
scan_timeout = 10

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "

[directory]
truncation_length = 1
read_only = ' 🔒'

[cmd_duration]
format = "[$duration]($style) "
style = "light_grey"
min_time = 1_000

[git_branch]
symbol = 'git'
format = '[$symbol:\([$branch](bold red)\)](bold blue) '

[git_status]
style = "bold yellow"
# format = '([\[$ahead$behind\]]($style))'
# ahead = '⇡$count'
# behind = '⇣$count'

