model = "gpt-5-codex"
model_reasoning_effort = "low"

[projects."/Users/lucas/work/monorepo"]
trust_level = "trusted"
approval_policy = "on-request"
sandbox_mode    = "workspace-write"

[projects."/Users/lucas"]
trust_level = "trusted"
