#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
FONT_FACE="UbuntuMono Nerd Font"
ICON_FONT="SF Pro"

sketchybar --add event aerospace_workspace_change

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/default.sh"

source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"

source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/net/group.sh"
source "$ITEM_DIR/audio.sh"

sketchybar --hotload true
sketchybar --update
